# This is an ugly 1st version of a librtl_433 build script for linux
# I successfully tested this on my Raspberry Pi 3b but it surely should be replaced by something more professional
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/abuf.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/am_analyze.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/baseband.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/bitbuffer.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/compat_time.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/config.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/data.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/data_printer_csv.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/data_printer_ext.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/data_printer_json.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/data_printer_jsonstr.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/data_printer_kv.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/data_printer_udp.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/decoder_util.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/demod.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/fileformat.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/librtl_433.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/list.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/mongoose.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/optparse.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/output_mqtt.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/pulse_analyze.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/pulse_demod.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/pulse_detect.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/r_util.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/redir_print.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/samp_grab.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/sdr.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/term_ctl.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/util.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/acurite.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/akhan_100F14.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/alecto.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ambient_weather.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ambientweather_tx8300.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ambientweather_wh31e.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/blyss.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/brennenstuhl_rcs_2044.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/bresser_3ch.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/bresser_5in1.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/bt_rain.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/calibeur.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/cardin.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/chuango.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/current_cost.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/danfoss.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/digitech_xc0324.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/dish_remote_6_3.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/dsc.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/efergy_e2_classic.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/efergy_optical.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/elro_db286a.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/elv.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/emontx.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/esa.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/esperanza_ews.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/fineoffset.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/fineoffset_wh1050.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/fineoffset_wh1080.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/flex.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/fordremote.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/fs20.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ft004b.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ge_coloreffects.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/generic_motion.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/generic_remote.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/generic_temperature_sensor.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/gt_wt_02.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/hideki.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/hondaremote.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/honeywell.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/honeywell_wdb.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ht680.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ibis_beacon.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/infactory.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/inovalley-kw9015b.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/interlogix.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/intertechno.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/kedsum.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/kerui.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/lacrosse.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/lacrosse_TX141TH_Bv2.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/lacrosse_tx35.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/lacrosse_ws7000.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/lacrossews.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/lightwave_rf.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/m_bus.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/maverick_et73.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/maverick_et73x.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/mebus.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/new_template.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/newkaku.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/nexa.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/nexus.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/oil_standard.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/oil_watchman.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/opus_xt300.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/oregon_scientific.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/oregon_scientific_sl109h.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/oregon_scientific_v1.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/philips.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/prologue.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/proove.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/quhwa.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/radiohead_ask.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/rftech.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/rubicson.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/s3318p.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/schraeder.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/silvercrest.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/simplisafe.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/smoke_gs558.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/solight_te44.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/springfield.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/steelmate.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tfa_pool_thermometer.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tfa_twin_plus_30.3049.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/thermopro_tp11.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/thermopro_tp12.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tpms_citroen.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tpms_ford.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tpms_jansite.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tpms_pmv107j.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tpms_renault.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/tpms_toyota.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/ttx201.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/vaillant_vrt340f.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/waveman.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/wg_pb12v1.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/wssensor.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/wt0124.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/wt450.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/x10_rf.c
gcc -Iinclude -lm -D RTLSDR -lrtlsdr -c src/devices/x10_sec.c
ar rcs librtl_433.a abuf.o am_analyze.o baseband.o bitbuffer.o compat_time.o config.o data.o data_printer_csv.o data_printer_ext.o data_printer_json.o data_printer_jsonstr.o data_printer_kv.o data_printer_udp.o decoder_util.o demod.o fileformat.o librtl_433.o list.o mongoose.o optparse.o output_mqtt.o pulse_analyze.o pulse_demod.o pulse_detect.o r_util.o redir_print.o samp_grab.o sdr.o term_ctl.o util.oacurite.o akhan_100F14.o alecto.o ambient_weather.o ambientweather_tx8300.o ambientweather_wh31e.o blyss.o brennenstuhl_rcs_2044.o bresser_3ch.o bresser_5in1.o bt_rain.o calibeur.o cardin.o chuango.o current_cost.o danfoss.o digitech_xc0324.o dish_remote_6_3.o dsc.o efergy_e2_classic.o efergy_optical.o elro_db286a.o elv.o emontx.o esa.o esperanza_ews.o fineoffset.o fineoffset_wh1050.o fineoffset_wh1080.o flex.o fordremote.o fs20.o ft004b.o ge_coloreffects.o generic_motion.o generic_remote.o generic_temperature_sensor.o gt_wt_02.o hideki.o hondaremote.o honeywell.o honeywell_wdb.o ht680.o ibis_beacon.o infactory.o inovalley-kw9015b.o interlogix.o intertechno.o kedsum.o kerui.o lacrosse.o lacrosse_TX141TH_Bv2.o lacrosse_tx35.o lacrosse_ws7000.o lacrossews.o lightwave_rf.o m_bus.o maverick_et73.o maverick_et73x.o mebus.o new_template.o newkaku.o nexa.o nexus.o oil_standard.o oil_watchman.o opus_xt300.o oregon_scientific.o oregon_scientific_sl109h.o oregon_scientific_v1.o philips.o prologue.o proove.o quhwa.o radiohead_ask.o rftech.o rubicson.o s3318p.o schraeder.o silvercrest.o simplisafe.o smoke_gs558.o solight_te44.o springfield.o steelmate.o tfa_pool_thermometer.o tfa_twin_plus_30.3049.o thermopro_tp11.o thermopro_tp12.o tpms_citroen.o tpms_ford.o tpms_jansite.o tpms_pmv107j.o tpms_renault.o tpms_toyota.o ttx201.o vaillant_vrt340f.o waveman.o wg_pb12v1.o wssensor.o wt0124.o wt450.o x10_rf.o x10_sec.o
